apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-chat-service
  template:
    metadata:
      labels:
        app: group-chat-service
    spec:
      containers:
      - name: group-chat-service
        image: group-chat-service:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 5004
        env:
        - name: USER_SERVICE_URL
          value: http://user-service:5001
        - name: MESSAGE_SERVICE_URL
          value: http://message-service:5002
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: group-chat-service
spec:
  selector:
    app: group-chat-service
  ports:
  - port: 5004
    targetPort: 5004
  type: NodePort 